import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navigation/navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: 'rgb(15 23 42)'}}>
        <Navbar />
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}